// Package numdata is the model layer for number formatting: what a locale's
// number data holds, and how it is written down.
//
// It sits between the generator and the library so that the two share one
// definition rather than each spelling the layout out. Nothing here formats
// anything. What is stored is what CLDR says -- the symbols a locale writes
// numbers with and the patterns it writes them in, as patterns -- and never
// what any of it produces. A field holding a formatted number would mean the
// layering had been violated.
package numdata

import (
	"sort"

	"github.com/go-quickjs/go-intl/internal/blob"
)

// Version is the encoding's version, written first so that data generated by
// an older command is refused rather than misread.
const Version = 1

// A Currency is what one currency is called in one locale.
type Currency struct {
	// Code is the ISO code, "EUR".
	Code string
	// Symbol is what the locale writes instead, and Narrow the shorter form
	// where the locale has one. Either may be empty, in which case the code
	// itself is written.
	Symbol string
	Narrow string
	// Names are the spelled-out names, one per plural category: a dollar and
	// two dollars are not the same word, and in Polish there are four.
	Names []CountedText
}

// A CountedText is a wording and the plural category it belongs to.
type CountedText struct {
	Count string
	Text  string
}

// Name returns the spelled-out name for a plural category, falling back to
// "other" as CLDR's own lookup does.
func (c Currency) Name(count string) string {
	var other string
	for _, n := range c.Names {
		if n.Count == count {
			return n.Text
		}
		if n.Count == "other" {
			other = n.Text
		}
	}
	return other
}

// Symbols are the marks a locale writes numbers with.
type Symbols struct {
	Decimal     string
	Group       string
	PercentSign string
	PlusSign    string
	MinusSign   string
	Exponential string
	NaN         string
	Infinity    string
	// CurrencyDecimal and CurrencyGroup are used in place of Decimal and Group
	// when money is written, where a locale distinguishes them. Empty means it
	// does not.
	CurrencyDecimal string
	CurrencyGroup   string
}

// Spacing is one of CLDR's currency-spacing rules: when a space has to be put
// between the currency and the number because neither side supplies one.
//
// "USD1.00" reads badly where "$1.00" does not, so CLDR says to insert a space
// when the character of the currency facing the number is neither a symbol nor
// a separator, and the character of the number facing it is a digit. The
// patterns are Unicode set expressions and are kept as CLDR writes them.
type Spacing struct {
	CurrencyMatch    string
	SurroundingMatch string
	InsertBetween    string
}

// A CompactPattern is one of the short or long forms a magnitude is written
// in: "0K" for a thousand, "0 million" for a million. Count is the plural
// category it applies to, since a language may write a million differently
// depending on how many there are.
type CompactPattern struct {
	Exponent int
	Count    string
	Pattern  string
}

// Locale is everything needed to write a number in one locale.
type Locale struct {
	// NumberingSystem is the name of the digits the locale uses, "latn" or
	// "arab", and Digits are those ten digits. Digits is empty when they are
	// the ASCII ones, which is most of the time.
	NumberingSystem string
	Digits          string

	Symbols Symbols

	// The patterns, as UTS #35 writes them: "#,##0.###", "¤#,##0.00".
	// They are kept as patterns and taken apart when a formatter is built,
	// because a pattern is a rule and what it produces is an answer.
	DecimalPattern    string
	PercentPattern    string
	CurrencyPattern   string
	AccountingPattern string

	// BeforeCurrency applies where the currency follows the number, and
	// AfterCurrency where it comes first.
	BeforeCurrency Spacing
	AfterCurrency  Spacing

	// MinimumGroupingDigits is how many digits the first group must have for
	// a separator to appear at all: two in Spanish and Polish, where 1234 is
	// written without one.
	MinimumGroupingDigits int

	// CompactShort and CompactLong are the compact forms, sorted by exponent.
	CompactShort []CompactPattern
	CompactLong  []CompactPattern

	// UnitPatterns join an amount to a spelled-out currency name, "{0} {1}",
	// one per plural category.
	UnitPatterns []CountedText

	// Currencies is sorted by code.
	Currencies []Currency
}

// Currency finds one currency's names.
func (l *Locale) Currency(code string) (Currency, bool) {
	i := sort.Search(len(l.Currencies), func(i int) bool {
		return l.Currencies[i].Code >= code
	})
	if i < len(l.Currencies) && l.Currencies[i].Code == code {
		return l.Currencies[i], true
	}
	return Currency{}, false
}

// Encode writes a locale's data.
//
// The layout is a version byte and then length-prefixed strings in a fixed
// order, which the blob package writes. It is deliberately dull: the seam that
// matters is the Source the bytes arrive through, not a clever encoding.
func Encode(l *Locale) []byte {
	w := blob.NewWriter(Version)
	for _, s := range l.strings() {
		w.String(s)
	}
	w.Uint(l.MinimumGroupingDigits)
	for _, set := range [][]CompactPattern{l.CompactShort, l.CompactLong} {
		w.Uint(len(set))
		for _, c := range set {
			w.Uint(c.Exponent)
			w.String(c.Count)
			w.String(c.Pattern)
		}
	}
	w.Uint(len(l.UnitPatterns))
	for _, u := range l.UnitPatterns {
		w.String(u.Count)
		w.String(u.Text)
	}
	w.Uint(len(l.Currencies))
	for _, c := range l.Currencies {
		w.String(c.Code)
		w.String(c.Symbol)
		w.String(c.Narrow)
		w.Uint(len(c.Names))
		for _, n := range c.Names {
			w.String(n.Count)
			w.String(n.Text)
		}
	}
	return w.Bytes()
}

// Decode reads what Encode wrote.
func Decode(b []byte) (*Locale, error) {
	r, err := blob.NewReader(b, Version)
	if err != nil {
		return nil, err
	}
	var l Locale
	for _, p := range l.fields() {
		*p = r.String()
	}
	l.MinimumGroupingDigits = r.Uint()

	for _, set := range []*[]CompactPattern{&l.CompactShort, &l.CompactLong} {
		n := r.Uint()
		if n < 0 || n > r.Left() {
			break
		}
		out := make([]CompactPattern, 0, n)
		for i := 0; i < n; i++ {
			exponent := r.Uint()
			count := r.String()
			pattern := r.String()
			out = append(out, CompactPattern{exponent, count, pattern})
		}
		*set = out
	}

	if n := r.Uint(); n >= 0 && n <= r.Left() {
		l.UnitPatterns = make([]CountedText, 0, n)
		for i := 0; i < n; i++ {
			count := r.String()
			text := r.String()
			l.UnitPatterns = append(l.UnitPatterns, CountedText{count, text})
		}
	}
	if n := r.Uint(); n >= 0 && n <= r.Left() {
		l.Currencies = make([]Currency, 0, n)
		for i := 0; i < n; i++ {
			var c Currency
			c.Code = r.String()
			c.Symbol = r.String()
			c.Narrow = r.String()
			names := r.Uint()
			if names < 0 || names > r.Left() {
				break
			}
			c.Names = make([]CountedText, 0, names)
			for j := 0; j < names; j++ {
				count := r.String()
				text := r.String()
				c.Names = append(c.Names, CountedText{count, text})
			}
			l.Currencies = append(l.Currencies, c)
		}
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return &l, nil
}

// fields are the string fields in the order they are written. Encode and
// Decode both walk this, so neither can add a field without the other.
func (l *Locale) fields() []*string {
	return []*string{
		&l.NumberingSystem, &l.Digits,
		&l.Symbols.Decimal, &l.Symbols.Group, &l.Symbols.PercentSign,
		&l.Symbols.PlusSign, &l.Symbols.MinusSign, &l.Symbols.Exponential,
		&l.Symbols.NaN, &l.Symbols.Infinity,
		&l.Symbols.CurrencyDecimal, &l.Symbols.CurrencyGroup,
		&l.DecimalPattern, &l.PercentPattern, &l.CurrencyPattern, &l.AccountingPattern,
		&l.BeforeCurrency.CurrencyMatch, &l.BeforeCurrency.SurroundingMatch,
		&l.BeforeCurrency.InsertBetween,
		&l.AfterCurrency.CurrencyMatch, &l.AfterCurrency.SurroundingMatch,
		&l.AfterCurrency.InsertBetween,
	}
}

func (l *Locale) strings() []string {
	ptrs := l.fields()
	out := make([]string, len(ptrs))
	for i, p := range ptrs {
		out[i] = *p
	}
	return out
}
