// Package numdata is the model layer for number formatting: what a locale's
// number data holds, and how it is written down.
//
// It sits between the generator and the library so that the two share one
// definition rather than each spelling the layout out. Nothing here formats
// anything. What is stored is what CLDR says -- the symbols a locale writes
// numbers with and the patterns it writes them in, as patterns -- and never
// what any of it produces. A field holding a formatted number would mean the
// layering had been violated.
package numdata

import (
	"encoding/binary"
	"fmt"
	"sort"
)

// Version is the encoding's version, written first so that data generated by
// an older command is refused rather than misread.
const Version = 1

// A Currency is what one currency is called in one locale.
type Currency struct {
	// Code is the ISO code, "EUR".
	Code string
	// Symbol is what the locale writes instead, and Narrow the shorter form
	// where the locale has one. Either may be empty, in which case the code
	// itself is written.
	Symbol string
	Narrow string
}

// Symbols are the marks a locale writes numbers with.
type Symbols struct {
	Decimal     string
	Group       string
	PercentSign string
	PlusSign    string
	MinusSign   string
	Exponential string
	NaN         string
	Infinity    string
	// CurrencyDecimal and CurrencyGroup are used in place of Decimal and Group
	// when money is written, where a locale distinguishes them. Empty means it
	// does not.
	CurrencyDecimal string
	CurrencyGroup   string
}

// Spacing is one of CLDR's currency-spacing rules: when a space has to be put
// between the currency and the number because neither side supplies one.
//
// "USD1.00" reads badly where "$1.00" does not, so CLDR says to insert a space
// when the character of the currency facing the number is neither a symbol nor
// a separator, and the character of the number facing it is a digit. The
// patterns are Unicode set expressions and are kept as CLDR writes them.
type Spacing struct {
	CurrencyMatch    string
	SurroundingMatch string
	InsertBetween    string
}

// Locale is everything needed to write a number in one locale.
type Locale struct {
	// NumberingSystem is the name of the digits the locale uses, "latn" or
	// "arab", and Digits are those ten digits. Digits is empty when they are
	// the ASCII ones, which is most of the time.
	NumberingSystem string
	Digits          string

	Symbols Symbols

	// The patterns, as UTS #35 writes them: "#,##0.###", "¤#,##0.00".
	// They are kept as patterns and taken apart when a formatter is built,
	// because a pattern is a rule and what it produces is an answer.
	DecimalPattern    string
	PercentPattern    string
	CurrencyPattern   string
	AccountingPattern string

	// BeforeCurrency applies where the currency follows the number, and
	// AfterCurrency where it comes first.
	BeforeCurrency Spacing
	AfterCurrency  Spacing

	// MinimumGroupingDigits is how many digits the first group must have for
	// a separator to appear at all: two in Spanish and Polish, where 1234 is
	// written without one.
	MinimumGroupingDigits int

	// Currencies is sorted by code.
	Currencies []Currency
}

// Currency finds one currency's names.
func (l *Locale) Currency(code string) (Currency, bool) {
	i := sort.Search(len(l.Currencies), func(i int) bool {
		return l.Currencies[i].Code >= code
	})
	if i < len(l.Currencies) && l.Currencies[i].Code == code {
		return l.Currencies[i], true
	}
	return Currency{}, false
}

// Encode writes a locale's data.
//
// The layout is a version byte and then length-prefixed strings in a fixed
// order. It is deliberately dull: the seam that matters is the Source the
// bytes arrive through, not a clever encoding, and a dull one can be read by
// eye when something disagrees.
func Encode(l *Locale) []byte {
	var b []byte
	b = append(b, Version)
	for _, s := range l.strings() {
		b = appendString(b, s)
	}
	b = binary.AppendUvarint(b, uint64(l.MinimumGroupingDigits))
	b = binary.AppendUvarint(b, uint64(len(l.Currencies)))
	for _, c := range l.Currencies {
		b = appendString(b, c.Code)
		b = appendString(b, c.Symbol)
		b = appendString(b, c.Narrow)
	}
	return b
}

// Decode reads what Encode wrote.
func Decode(b []byte) (*Locale, error) {
	if len(b) == 0 {
		return nil, fmt.Errorf("numdata: the data is empty")
	}
	if b[0] != Version {
		return nil, fmt.Errorf("numdata: the data is version %d, not %d", b[0], Version)
	}
	r := reader{b: b[1:]}

	var l Locale
	fields := l.fields()
	for _, p := range fields {
		s, err := r.string()
		if err != nil {
			return nil, err
		}
		*p = s
	}
	n, err := r.uvarint()
	if err != nil {
		return nil, err
	}
	l.MinimumGroupingDigits = int(n)

	count, err := r.uvarint()
	if err != nil {
		return nil, err
	}
	if count > uint64(len(r.b)) {
		return nil, fmt.Errorf("numdata: %d currencies in %d bytes", count, len(r.b))
	}
	l.Currencies = make([]Currency, 0, count)
	for i := uint64(0); i < count; i++ {
		var c Currency
		for _, p := range []*string{&c.Code, &c.Symbol, &c.Narrow} {
			s, err := r.string()
			if err != nil {
				return nil, err
			}
			*p = s
		}
		l.Currencies = append(l.Currencies, c)
	}
	if len(r.b) != 0 {
		return nil, fmt.Errorf("numdata: %d bytes left over", len(r.b))
	}
	return &l, nil
}

// fields are the string fields in the order they are written. Encode and
// Decode both walk this, so neither can add a field without the other.
func (l *Locale) fields() []*string {
	return []*string{
		&l.NumberingSystem, &l.Digits,
		&l.Symbols.Decimal, &l.Symbols.Group, &l.Symbols.PercentSign,
		&l.Symbols.PlusSign, &l.Symbols.MinusSign, &l.Symbols.Exponential,
		&l.Symbols.NaN, &l.Symbols.Infinity,
		&l.Symbols.CurrencyDecimal, &l.Symbols.CurrencyGroup,
		&l.DecimalPattern, &l.PercentPattern, &l.CurrencyPattern, &l.AccountingPattern,
		&l.BeforeCurrency.CurrencyMatch, &l.BeforeCurrency.SurroundingMatch,
		&l.BeforeCurrency.InsertBetween,
		&l.AfterCurrency.CurrencyMatch, &l.AfterCurrency.SurroundingMatch,
		&l.AfterCurrency.InsertBetween,
	}
}

func (l *Locale) strings() []string {
	ptrs := l.fields()
	out := make([]string, len(ptrs))
	for i, p := range ptrs {
		out[i] = *p
	}
	return out
}

func appendString(b []byte, s string) []byte {
	b = binary.AppendUvarint(b, uint64(len(s)))
	return append(b, s...)
}

type reader struct{ b []byte }

func (r *reader) uvarint() (uint64, error) {
	v, n := binary.Uvarint(r.b)
	if n <= 0 {
		return 0, fmt.Errorf("numdata: a length is cut short")
	}
	r.b = r.b[n:]
	return v, nil
}

func (r *reader) string() (string, error) {
	n, err := r.uvarint()
	if err != nil {
		return "", err
	}
	if n > uint64(len(r.b)) {
		return "", fmt.Errorf("numdata: a string of %d bytes with %d left", n, len(r.b))
	}
	s := string(r.b[:n])
	r.b = r.b[n:]
	return s, nil
}
